"""empty message

Revision ID: 4c4146f463a4
Revises:
Create Date: 2019-08-14 15:15:25.042389

"""
from alembic import op
import sqlalchemy as sa
import db_helpers


# revision identifiers, used by Alembic.
revision = '4c4146f463a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('_model_type', sa.String(length=50), nullable=True),
    sa.Column('id', db_helpers.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contest',
    sa.Column('key', db_helpers.UUID(), nullable=True),
    sa.Column('held_in', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', db_helpers.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contest_key'), ['key'], unique=False)

    op.create_table('name',
    sa.Column('winner', sa.Boolean(), nullable=False),
    sa.Column('contest_id', db_helpers.UUID(), nullable=True),
    sa.Column('id', db_helpers.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], ),
    sa.ForeignKeyConstraint(['id'], ['base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('name', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_name_winner'), ['winner'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('name', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_name_winner'))

    op.drop_table('name')
    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contest_key'))

    op.drop_table('contest')
    op.drop_table('base')
    # ### end Alembic commands ###
