"""empty message

Revision ID: 825dbdf19fcb
Revises: 89ab1f6b5fb6
Create Date: 2020-03-16 14:09:51.721377

"""
from alembic import op
import sqlalchemy as sa
import db_helpers

# revision identifiers, used by Alembic.
revision = '825dbdf19fcb'
down_revision = '89ab1f6b5fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private_key', db_helpers.UUID(), nullable=True))
        batch_op.add_column(sa.Column('public_key', db_helpers.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_contest_private_key'), ['private_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_contest_public_key'), ['public_key'], unique=False)
        batch_op.drop_index('ix_contest_key')
        batch_op.drop_column('key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.VARCHAR(), nullable=True))
        batch_op.create_index('ix_contest_key', ['key'], unique=False)
        batch_op.drop_index(batch_op.f('ix_contest_public_key'))
        batch_op.drop_index(batch_op.f('ix_contest_private_key'))
        batch_op.drop_column('public_key')
        batch_op.drop_column('private_key')

    # ### end Alembic commands ###
