"""empty message

Revision ID: 89ab1f6b5fb6
Revises: 4c4146f463a4
Create Date: 2019-08-14 15:59:09.399506

"""
from alembic import op
import sqlalchemy as sa, db_helpers


# revision identifiers, used by Alembic.
revision = '89ab1f6b5fb6'
down_revision = '4c4146f463a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_base_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_base_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_base_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_base_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_base_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contest_held_in'), ['held_in'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contest_held_in'))

    with op.batch_alter_table('base', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_base_updated_at'))
        batch_op.drop_index(batch_op.f('ix_base_slug'))
        batch_op.drop_index(batch_op.f('ix_base_name'))
        batch_op.drop_index(batch_op.f('ix_base_deleted'))
        batch_op.drop_index(batch_op.f('ix_base_created_at'))

    # ### end Alembic commands ###
